version: 2

on:
  push:
    branches-ignore:
      - 'gh-pages'

jobs:

  test_ubuntu_rolling_python3:
    docker:
      - image: ubuntu:rolling
    steps:
      - run: echo "nothing to do for the gh-pages branch"

workflows:

  version: 2
  test-matrix:
    jobs:
      - test_ubuntu_rolling_python3
