name: ci_rust

on:
  push:
    paths:
      - "do.py"
      - ".github/workflows/rust.yml"
      - "code-experiments/build/rust/**"
      - "code-experiments/src/**.c"
      - "code-experiments/src/**.h"
  pull_request:
    branches: [ master, development ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install click
    - run: python ${{github.workspace}}/do.py build-rust
